name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test-tag:
        description: 'Select tag to run'
        required: false
        default: ''
        type: choice
        options:
          - '@smoke'
          - '@regression'
          - '@negative'
          - 'all'
      browser:
        description: 'Select browser to run tests'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'chromium'
          - 'firefox'
          - 'webkit'

  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create .env.local
        run: |
          cp .env .env.local || true
          echo ".env copied to .env.local"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clean old test results
        run: rm -rf allure-results allure-report reports

      - name: Run Playwright tests
        run: |
          TAG="${{ github.event.inputs.test-tag || '' }}"
          BROWSER="${{ github.event.inputs.browser || 'all' }}"

          if [[ "$BROWSER" == "all" ]]; then
            PROJECTS="--project=chromium --project=firefox --project=webkit"
          else
            PROJECTS="--project=$BROWSER"
          fi

          if [[ -n "$TAG" && "$TAG" != "all" ]]; then
            npx playwright test --grep "$TAG" $PROJECTS --reporter=line,html,allure-playwright
          else
            npx playwright test $PROJECTS --reporter=line,html,allure-playwright
          fi

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: reports/
          retention-days: 30